export default function recommendPic(conditionText) {
    const weatherImages = {
        "sunny": "sunny.jpg",
        "clear": "sunny.jpg",
        "partly cloudy": "cloudy.jpg",
        "cloudy": "cloudy.jpg",
        "overcast": "cloudy.jpg",
        "mist": "misty.jpg",
        "patchy rain possible": "rainy.jpg",
        "patchy snow possible": "snowy.jpg",
        "patchy sleet possible": "snowy.jpg",
        "dust": "cloudy.jpg",
        "fog": "misty.jpg",
        "freezing fog": "misty.jpg",
        "shallow fog": "misty.jpg",
        "light rain shower": "rainy.jpg",
        "moderate rain shower": "rainy.jpg",
        "heavy rain shower": "rainy.jpg",
        "light snow shower": "snowy.jpg",
        "moderate snow shower": "snowy.jpg",
        "heavy snow shower": "snowy.jpg",
        "light sleet shower": "snowy.jpg",
        "moderate sleet shower": "snowy.jpg",
        "heavy sleet shower": "snowy.jpg",
        "light rain": "rainy.jpg",
        "moderate rain": "rainy.jpg",
        "heavy rain": "rainy.jpg",
        "light snow": "snow.png",
        "moderate snow": "snow.png",
        "heavy snow": "snow.png",
        "light sleet": "snowy.jpg",
        "moderate sleet": "snowy.jpg",
        "heavy sleet": "snowy.jpg",
        "thunder shower": "thunderstorm.jpg",
        "thunder shower with hail": "thunderstorm.jpg",
        "blowing snow": "snowy.jpg",
        "blizzard": "snowy.jpg",
        "dust storm": "cloudy.jpg",
        "sandstorm": "cloudy.jpg",
        "tropical storm": "cloudy.jpg",
        "hurricane": "cloudy.jpg",
        "freezing drizzle": "snowy.jpg",
        "light freezing rain": "snowy.jpg",
        "moderate freezing rain": "snowy.jpg",
        "heavy freezing rain": "snowy.jpg",
        "hail": "thunderstorm.jpg",
        "thunderstorm": "thunderstorm.jpg",
        "thunderstorm with hail": "thunderstorm.jpg",
        "severe thunderstorms": "thunderstorm.jpg",
        "ice pellets": "snowy.jpg",
        "snow flurries": "snowy.jpg",
        "snow showers": "snowy.jpg",
        "severe dust storm": "cloudy.jpg",
        "light showers of rain and snow": "rainy.jpg",
        "showers of rain and snow": "rainy.jpg",
        "heavy showers of rain and snow": "rainy.jpg"
    };
    console.log(weatherImages[conditionText.toLowerCase()]);

    return weatherImages[conditionText.toLowerCase()] || "default.jpg";
}
